"""empty message

Revision ID: 664679d72627
Revises: b6e91eaea937
Create Date: 2018-03-05 14:11:22.649961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664679d72627'
down_revision = 'b6e91eaea937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
